#!/usr/bin/env python3

import os
import subprocess

from deploy import Deploy

path = os.path.dirname(os.path.abspath(__file__))
deploy = Deploy(path)

# deploy.build_odoo()
deploy.odoo_core()
deploy.odoo_enterprise()
deploy.odoo_addons()

print('\n==== Odoo configuration ====')
print('(i) odoo_root: %s' % deploy.odoo_root)

# Remove file, with old/former config.
# File gets re-created upon start odoo.
try:
    os.remove('/root/.odoorc')
except OSError:
    pass

path_start_odoo = '{path}/start_odoo.py'.format(path=path)
subprocess.run(path_start_odoo, shell=True)
