#!/usr/bin/env python3

import os
import subprocess
import sys

from deploy import Deploy
from start_odoo import StartOdoo

path = os.path.dirname(os.path.abspath(__file__))
deploy = Deploy(path)

# deploy.build_odoo()
deploy.odoo_core()
deploy.odoo_enterprise()
deploy.odoo_addons()

print('\n==== Odoo configuration ====')
print('(i) odoo_root_dir: %s' % deploy.odoo_root_dir)

# Remove file, with old/former config.
# File gets re-created upon start odoo.
try:
    os.remove('/root/.odoorc')
except OSError:
    pass

if __name__ == '__main__':
    argv = sys.argv[1:]
    start_odoo = StartOdoo(argv)
    start_odoo.run()
